[package]
name = "gemmit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
reqwest = "0.12.12"
serde_json = "1.0.139"
tokio = {version = "1.43.0", features = ["full"]}
